*.kicad_pcb linguist-detectable=true
*.sch linguist-detectable=true
tools/export_bom.py linguist-detectable=false


/* INSERINDO REGISTROS NA TABELA */

INSERT INTO seriea(id,Nome_Time, Pontos, VIT, EMP, DERR) VALUES(1,'PALMEIRAS',49,14,7,2);
INSERT INTO seriea(id,Nome_Time, Pontos, VIT, EMP, DERR) VALUES(2,'FLUMINENSE',41,12,5,6);
INSERT INTO seriea (id,Nome_Time, Pontos, VIT, EMP, DERR) VALUES(3,'FLAMENGO',40,12,4,7);
INSERT INTO seriea (id,Nome_Time, Pontos, VIT, EMP, DERR) VALUES(4,'CORINTHIANS',39,11,6,6);
INSERT INTO seriea (id,Nome_Time, Pontos, VIT, EMP, DERR) VALUES(5,'INTERNACIONAL',39,10,9,4);
INSERT INTO seriea (id,Nome_Time, Pontos, VIT, EMP, DERR) VALUES(6,'ATHLETICO-PR',38,11,5,7);
INSERT INTO seriea (id,Nome_Time, Pontos, VIT, EMP, DERR) VALUES(7,'ATLÉTICO-MG',35,9,8,6);
INSERT INTO seriea (id,Nome_Time, Pontos, VIT, EMP, DERR) VALUES(8,'SANTOS',33,8,9,6);
INSERT INTO seriea (id,Nome_Time, Pontos, VIT, EMP, DERR) VALUES(9,'AMÉRICA-MG',31,9,4,10);
INSERT INTO seriea (id,Nome_Time, Pontos, VIT, EMP, DERR) VALUES(10,'BRAGANTINO',31,8,7,8);
INSERT INTO seriea (id,Nome_Time, Pontos, VIT, EMP, DERR) VALUES(11,'GOIÁS',29,7,8,8);
INSERT INTO seriea (id,Nome_Time, Pontos, VIT, EMP, DERR) VALUES(12,'SÃO PAULO',29,6,11,6);
INSERT INTO seriea (id,Nome_Time, Pontos, VIT, EMP, DERR) VALUES(13,'FORTALEZA',27,7,6,10);
INSERT INTO seriea (id,Nome_Time, Pontos, VIT, EMP, DERR) VALUES(14,'BOTAFOGO',27,7,6,10);
INSERT INTO seriea (id,Nome_Time, Pontos, VIT, EMP, DERR) VALUES(15,'CEARÁ-SC',26,5,11,7);
INSERT INTO seriea (id,Nome_Time, Pontos, VIT, EMP, DERR) VALUES(16,'CUIABÁ',24,6,6,11);
INSERT INTO seriea (id,Nome_Time, Pontos, VIT, EMP, DERR) VALUES(17,'AVAÍ',23,6,5,12);
INSERT INTO seriea (id,Nome_Time, Pontos, VIT, EMP, DERR) VALUES(18,'CORITIBA',22,6,4,13);
INSERT INTO seriea (id,Nome_Time, Pontos, VIT, EMP, DERR) VALUES(19,'ATLÉTICO-GO',22,5,7,11);
INSERT INTO seriea (id,Nome_Time, Pontos, VIT, EMP, DERR) VALUES(20,'JUVENTUDE',17,3,8,12);

/* SELECIONANDO ALL REGISTROS */
SELECT * FROM seriea; 

/*  CRIANDO AGREGAÇÕES: WIN_RATE , DEFEAT_RATE, TIE_RATE */
SELECT *, 
(VIT + EMP + DERR) as TOTAL, /* TOTAL DE PARTIDAS */
ROUND((VIT / (VIT+EMP+DERR)) * 100,2) AS WIN_RATE, /* COLUNA WIN_RATE */
ROUND((EMP / (VIT+EMP+DERR)) * 100,2) AS TIE_RATE, /* COLUNA TIE_RATE */
ROUND((DERR / (VIT+EMP+DERR)) * 100,2) AS DEFEAT_RATE /* COLUNA DEFEAT_RATE */
FROM seriea; 



 /* SELECIONANDO APENAS OS TIMES QUE POSSUEM O WINRATE > 50 */
 /* Por que o uso do HAVING? Pois, o WHERE só serve para filtar registros enquanto o HAVING serve para filtar agregações como por exemplo o WINRATE*/
 /* ROUND --> Para reduzir as casas decimais e deixar um valor mais 'absoluto' */
SELECT *, 
(VIT + EMP + DERR) as TOTAL, /* TOTAL DE PARTIDAS */
ROUND((VIT / (VIT+EMP+DERR)) * 100,2) AS WIN_RATE FROM seriea /* WINRATE DE CADA TIME */
HAVING WIN_RATE > 50;

/* SELECIONANDO APENAS OS TIMES QUE POSSUEM O WINRATE > 30 OR TIE_RATE < 10 */
SELECT *, 
(VIT + EMP + DERR) as TOTAL, 
ROUND((VIT / (VIT+EMP+DERR)) * 100,2) AS WIN_RATE, 
ROUND((EMP / (VIT+EMP+DERR)) * 100,2) AS TIE_RATE, 
ROUND((DERR / (VIT+EMP+DERR)) * 100,2) AS DEFEAT_RATE 
FROM seriea
GROUP BY WIN_RATE
HAVING WIN_RATE > 30 OR TIE_RATE < 10;


/* TOP 10 TIMES COM MAIORES DEFEAT_RATE */
SELECT *,
ROUND((DERR / (VIT+EMP+DERR) * 100), 2) AS DEFEAT_RATE
FROM seriea
ORDER BY DEFEAT_RATE DESC
LIMIT 10;

/* TOP 10 TIMES COM MAIORES TIE_RATE */
SELECT *,
ROUND((EMP / (VIT+EMP+DERR) * 100), 2) AS TIE_RATE
FROM seriea
ORDER BY TIE_RATE DESC
LIMIT 10;

/* SELECIONANDO TIMES QUE POSSUEM REGISTROS SIMULTÂNEOS*/
SELECT * FROM seriea
WHERE (VIT = EMP OR VIT = DERR)

/* SELECIONANDO TIMES QUE POSSUEM O NÚMERO DE VITORIAS  DENTRO DO INTERVALO DE 5 -> 10*/
SELECT * FROM seriea
WHERE VIT BETWEEN 5 and 10 ;

/* SELECIONANDO TIMES QUE POSSUEM UM NÚMERO DE VITORIAS ESPECÍFICO */
SELECT * FROM seriea
WHERE VIT IN (5, 6, 7);




